# Name of your application. Used to uniquely configure containers.
service: next-carcenter-erding

# Name of the container image.
image: devrico003/next-carcenter-erding-kamal

# Deploy to these servers.
servers:
  web:
    hosts:
      -  84.247.136.227
    labels:
      traefik.http.routers.kiqr_cloud.rule: Host(`kamal.devrico003.com`)
      traefik.http.routers.kiqr_cloud_secure.entrypoints: websecure
      traefik.http.routers.kiqr_cloud_secure.rule: Host(`kamal.devrico003.com`)
      traefik.http.routers.kiqr_cloud_secure.tls: true
      traefik.http.routers.kiqr_cloud_secure.tls.certresolver: letsencrypt


traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json" 
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "palermo003@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web 

registry:
  username: 
    - DOCKERHUB_USERNAME

  # Always use an access token rather than real password when possible.
  password:
    - DOCKERHUB_TOKEN

env:
  clear:
    DB_HOST: 173.249.33.169
  secret:
    - ENCODED_CREDENTIALS
    - SENDGRID_API_KEY
    - MONGODB_URI
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
    - AWS_BUCKET_NAME
  


accessories:
  db:
    image: mongo
    host: 173.249.33.169
    port: 27017
    env:
      clear:

      secret:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
    directories:
      - data:/data/db
