name: CI/CD Pipeline

on:
  push:
    branches: 
      - main

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  build:
    needs: source
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: npm test

  security_and_notify:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@0.3.0
      with:
        args: --severity-threshold=high
        fail-on-issues: true
    - name: Send failure notification
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: CI/CD Pipeline failed
        to: ${{secrets.MAIL}}
        body: The pipeline has failed. Please check the GitHub Actions output.